In [1]:
import numpy as np

x = 6
x

6

In [2]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [3]:
x.shape

(3,)

In [5]:
np.argmax

<function argmax at 0x123b1ac30>

argmax = array가 [1,2,3]인데 왜 2가 나오냐면 index 즉 0, 1, 2 이고 2의 자리가 가장 큰 3이란 값이 들어가기 때문

즉 array 가 만약 [1, 3, 2]일 경우 argmax는 1이 나옴 1번째 자리가 가장 크기 때문

In [6]:
np.argmax(x)

3

In [7]:
y = np.array([1, 2, 3])

In [8]:
y

array([1, 2, 3])

In [9]:
np.argmax(y)

2

In [10]:
y.argmax

<function ndarray.argmax>

In [11]:
y.argmax()

2

In [12]:
y = np.array([1, 3, 2])
y

array([1, 3, 2])

In [13]:
y.argmax()

1

In [14]:
z = np.array([[1, 2, 3], [2, 3, 4], [5, 6, 7]])
z

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [15]:
z.shape

(3, 3)

In [16]:
z.argmax()

8

In [17]:
a = np.array([[[1, 2, 3], [2, 3, 4]], [[5, 6, 7], [8, 9, 10]]])
a

array([[[ 1,  2,  3],
        [ 2,  3,  4]],

       [[ 5,  6,  7],
        [ 8,  9, 10]]])

In [18]:
a.shape

(2, 2, 3)

In [19]:
a.argmax()

11

a의 경우 세로3, 가로3, 너비 4인 직사각형 (2, 2, 3) => 가로2, 세로2, 너비3임

In [21]:
arr = np.array([[1,2,3], [4, 5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
a.shape

(2, 2, 3)

In [23]:
print(arr[:2, 1])

[2 5]


In [24]:
print(arr[:2, :1])

[[1]
 [4]]


In [25]:
print(arr[:2, 2:])

[[3]
 [6]]


In [26]:
print(arr[:2, 1:])

[[2 3]
 [5 6]]


In [27]:
print(arr[:, 2:])

[[3]
 [6]
 [9]]


In [28]:
print(arr[2:, :])

[[7 8 9]]


In [29]:
print(arr[:, 1:])

[[2 3]
 [5 6]
 [8 9]]


In [30]:
print(arr[:, :1])

[[1]
 [4]
 [7]]


In [31]:
print(arr[:, :2])

[[1 2]
 [4 5]
 [7 8]]


In [32]:
print(arr[1:, :])

[[4 5 6]
 [7 8 9]]


In [33]:
print(arr[:, 2:])

[[3]
 [6]
 [9]]


In [34]:
print(arr[:, :2])

[[1 2]
 [4 5]
 [7 8]]


In [35]:
print(arr[:, :2].shape)

(3, 2)


In [36]:
arr = np.array([[1,2,3], [4, 5,6],[7,8,9], [11, 12, 13]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [37]:
print(arr[1:, :1])

[[ 4]
 [ 7]
 [11]]


In [38]:
print(arr[:2, :2])

[[1 2]
 [4 5]]


In [39]:
print(arr[:2, 2:])

[[3]
 [6]]


In [40]:
print(arr[2:, 2:])

[[ 9]
 [13]]


In [41]:
print(arr[2:, 1:])

[[ 8  9]
 [12 13]]


In [42]:
print(arr[:2, :])

[[1 2 3]
 [4 5 6]]


In [43]:
print(arr[1:, :2])

[[ 4  5]
 [ 7  8]
 [11 12]]


In [44]:
print(arr[2:, :2])

[[ 7  8]
 [11 12]]


In [45]:
arr = np.array([[1,2,3], [4, 5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

백터의 내적 : 내적은 각 element의 곱을 모두 더한 것이다

In [47]:
a = np.array([2, 5, 1])
d = np.array([4, 3, 5])

np.dot(a,d)

28

Matrix 곱셈 (행렬 곱셈) : 두 행렬을 곱한다?

In [48]:
a = np.array([[2,1], [1, 4]])
b = np.array([[1, 2, 0], [0, 1, 2]])

np.matmul(a, b)

array([[2, 5, 2],
       [1, 6, 8]])

전치 행렬 : colume과 row가 바뀐다?

In [50]:
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [51]:
np.arrange(9)

AttributeError: module 'numpy' has no attribute 'arrange'

In [52]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
A = np.arange(9)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
B = A.reshape(3, 3)

In [56]:
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
B.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [58]:
np.transpose(B)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])