In [1]:
import numpy as np
import pandas as pd

DataFrame : 여러 개의 Series를 같은 index 기준으로 모아 Table을 만든것

In [4]:
np.random?

Type:        module
String form: <module 'numpy.random' from '/opt/anaconda3/lib/python3.12/site-packages/numpy/random/__init__.py'>
File:        /opt/anaconda3/lib/python3.12/site-packages/numpy/random/__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
PCG64DXSM
Philox
SFC64
============================================= ===

============================================= ===
Getting entropy to initialize a 

In [9]:
np.random.seed(101)
data = np.random.randn(5,4)
print(data)

[[ 2.70684984  0.62813271  0.90796945  0.50382575]
 [ 0.65111795 -0.31931804 -0.84807698  0.60596535]
 [-2.01816824  0.74012206  0.52881349 -0.58900053]
 [ 0.18869531 -0.75887206 -0.93323722  0.95505651]
 [ 0.19079432  1.97875732  2.60596728  0.68350889]]


In [7]:
data.shape

(5, 4)

In [10]:
data.argmax()

0

In [12]:
df = pd.DataFrame(data, columns=['W', 'X', 'Y', 'Z'])
df

W         X         Y         Z
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [13]:
df.columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [14]:
dr.info

NameError: name 'dr' is not defined

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   W       5 non-null      float64
 1   X       5 non-null      float64
 2   Y       5 non-null      float64
 3   Z       5 non-null      float64
dtypes: float64(4)
memory usage: 292.0 bytes


In [16]:
df.describe()

W         X         Y         Z
count  5.000000  5.000000  5.000000  5.000000
mean   0.343858  0.453764  0.452287  0.431871
std    1.681131  1.061385  1.454516  0.594708
min   -2.018168 -0.758872 -0.933237 -0.589001
25%    0.188695 -0.319318 -0.848077  0.503826
50%    0.190794  0.628133  0.528813  0.605965
75%    0.651118  0.740122  0.907969  0.683509
max    2.706850  1.978757  2.605967  0.955057

In [17]:
df['W']

0    2.706850
1    0.651118
2   -2.018168
3    0.188695
4    0.190794
Name: W, dtype: float64

DataFrame indexing

In [18]:
df['W']

0    2.706850
1    0.651118
2   -2.018168
3    0.188695
4    0.190794
Name: W, dtype: float64

In [20]:
df.W

0    2.706850
1    0.651118
2   -2.018168
3    0.188695
4    0.190794
Name: W, dtype: float64

In [21]:
df.type

AttributeError: 'DataFrame' object has no attribute 'type'

In [22]:
type(df.W)

pandas.core.series.Series

In [23]:
df[['W', 'X', 'Y']]

W         X         Y
0  2.706850  0.628133  0.907969
1  0.651118 -0.319318 -0.848077
2 -2.018168  0.740122  0.528813
3  0.188695 -0.758872 -0.933237
4  0.190794  1.978757  2.605967

new Colume 추가 및 삭제

In [24]:
df['new'] = df['X'] + df['Y']

In [25]:
df

W         X         Y         Z       new
0  2.706850  0.628133  0.907969  0.503826  1.536102
1  0.651118 -0.319318 -0.848077  0.605965 -1.167395
2 -2.018168  0.740122  0.528813 -0.589001  1.268936
3  0.188695 -0.758872 -0.933237  0.955057 -1.692109
4  0.190794  1.978757  2.605967  0.683509  4.584725

In [27]:
df.drop("new", axis =1, inplace = True )

In [28]:
df

W         X         Y         Z
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [29]:
df

W         X         Y         Z
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [30]:
df.shape

(5, 4)

Missing Data 처리

In [31]:
import pandas as pd
import numpy as np

df.dropNa()

AttributeError: 'DataFrame' object has no attribute 'dropNa'

In [32]:
df = pd.DataFrame({"A": [1,2,3]}),
                    "B": [567]

IndentationError: unexpected indent (1738760457.py, line 2)

In [33]:
df = pd.DataFrame({'A':[1, 2, np.nan], 'B':[5, np.nan, np.nan], 'C':[1,2,3]})

In [34]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [35]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [36]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [37]:
df.fillna(0)

A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

In [38]:
df.fillna(1)

A    B  C
0  1.0  5.0  1
1  2.0  1.0  2
2  1.0  1.0  3

In [39]:
df = pd.read_csv("winequailty-red.csv")
df

FileNotFoundError: [Errno 2] No such file or directory: 'winequailty-red.csv'